Entities extended from base
leinadpy/tienda-online-backend pull request #12
Opened 2023-09-11 19:44 UTC by Gaston71

Extendidas todas las entidades de base como sugeriste. Lo hicimos en vivo en el zoom pero habia faltado subir los cambios acá.

2023-09-12 01:44 UTC, leinadpy requested changes
Hay un cambio sustancial que debemos hacer, los ids de las entidades ya no son necesarias.
Como se extiende de base.entity.ts, donde ya esta definida el id, no es necesario volver a agregarlo.

Puedes corregir eso para asi ponerlo bien?

2023-09-12 20:32 UTC, Gaston71 commented
> Hay un cambio sustancial que debemos hacer, los ids de las entidades ya no son necesarias. Como se extiende de base.entity.ts, donde ya esta definida el id, no es necesario volver a agregarlo.
> 
> Puedes corregir eso para asi ponerlo bien?

Lo intentaré.

2023-09-12 20:53 UTC, Gaston71 commented
Listo!

2023-09-13 02:56 UTC, leinadpy approved these changes

2023-09-13 02:56 UTC, merged