Agregadas relaciones de tablas y validaciones de los DTO con class-va…
leinadpy/tienda-online-backend pull request #13
Opened 2023-09-16 03:03 UTC by dartorrejon

Agregadas las relaciones entre tablas y modificado tambien validaciones de los DTO con class-validator, extra corregido el nombre de shooping-cart a shopping-cart

2023-09-17 22:54 UTC, leinadpy requested changes
Favor mirar los cambios necesarios. @dartorrejon

2023-09-17 22:54 UTC, leinadpy commented on src/cart_product/entities/cart_product.entity.ts
> +  @ManyToOne(() => ShoppingCart, (shopping_cart) => shopping_cart.cart_prudocts)
se puede corregir poniendo shopping_cart.cart_products

2023-09-17 22:54 UTC, leinadpy commented on src/cart_product/entities/cart_product.entity.ts
>  //TODO: FK cart_id
Remover los comentarios que ya resuelven los TODOs pendientes.

2023-09-17 22:54 UTC, leinadpy commented on src/cart_product/entities/cart_product.entity.ts
>  //TODO: FK product_id
Remover los comentarios que ya resuelven los TODOs pendientes.

2023-09-17 22:54 UTC, leinadpy commented on src/customers/dto/create-customer.dto.ts
> +    register_date: Date;
No es necesario pasarle la fecha por medio del DTO, esto se puede asignar directamente en el servidor con una función para tomar la fecha actual al momento de crear el registro.

2023-09-17 22:54 UTC, leinadpy commented on src/customers/entities/customer.entity.ts
> -  // TODO: relaciones
Remover los comentarios que ya resuelven los TODOs pendientes.

2023-09-17 22:54 UTC, leinadpy commented on src/orders/entities/order.entity.ts
>  //import { ShoppingCart } from '../../shopping-cart/entities/shopping-cart.entity.ts'; // Import your ShoppingCart entity here
eliminar comentarios que ya no son utilizados.

2023-09-17 22:54 UTC, leinadpy commented on src/orders/entities/order.entity.ts
>    // TODO: relaciones
Remover los comentarios que ya resuelven los TODOs pendientes.

2023-09-17 22:54 UTC, leinadpy commented on src/shopping-cart/dto/create-shopping-cart.dto.ts
>  export enum Status {
Generalmente tanto los enums como las interfaces se suelen poner en una carpeta a parte en un archivo separados, algo como enums/status.enum.ts

2023-09-17 22:54 UTC, leinadpy commented on src/shopping-cart/dto/create-shopping-cart.dto.ts
> +    @IsString()
Existe un validador para los enums, @IsEnum(Status)

Aunque pienso que para el createDto no sería necesario, se puede poner que al crear el carrito por defecto el valor sea OPEN.

Solo para el updateDto definiríamos el enum de status para poder actualizar el carrito.

2023-09-17 22:54 UTC, leinadpy commented on src/shopping-cart/dto/create-shopping-cart.dto.ts
>      startedAt: Date
Creo que podemos manejarlo con una función a la hora de crear el registro para el shopping_cart.
No sería necesario en el DTO.

2023-09-17 22:54 UTC, leinadpy commented on src/shopping-cart/dto/update-shopping-cart.dto.ts
> +export class UpdateShoppingCartDto extends PartialType(CreateShoppingCartDto) {}
Siguiendo con el comentario del CreateShoppingCartDto, deberíamos aquí definir el status con el enum, poniendo como opcional que pueda venir o no esta propiedad.

Para este caso particular, como las otras propiedades de customer_id y startedAt no deberían ser posibles ser actualizadas, no sería necesario extender del dto de CreateShoppingCartDto, se puede manejar como un dto independiente.

2023-09-17 22:54 UTC, leinadpy commented on src/shopping-cart/entities/shopping-cart.entity.ts
> +    enum: ['OPEN', 'CLOSED', 'CANCELED'],
se puede setear el enum directamente con el Enum.
enum: Status

2023-09-17 22:54 UTC, leinadpy commented on src/shopping-cart/entities/shopping-cart.entity.ts
> +  cart_prudocts: CartProduct[];
corregir para ponerlo como cart_products.

2023-09-17 22:54 UTC, leinadpy commented on src/shopping-cart/entities/shopping-cart.entity.ts
> +  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' }) //No se si es lo correcto
Está correcto.
Sería bueno que todos los campos que son de tipo fecha que se setean de forma automática la fecha, manejar el mismo estandar.

2023-09-19 21:44 UTC, dartorrejon commented on src/cart_product/entities/cart_product.entity.ts
> +  @ManyToOne(() => ShoppingCart, (shopping_cart) => shopping_cart.cart_prudocts)
cambio realizado

2023-09-19 21:44 UTC, dartorrejon commented on src/cart_product/entities/cart_product.entity.ts
>  //TODO: FK cart_id
Comentarios eliminados

2023-09-19 21:44 UTC, dartorrejon commented on src/cart_product/entities/cart_product.entity.ts
>  //TODO: FK product_id
Comentarios removidos

2023-09-19 21:45 UTC, dartorrejon commented on src/customers/dto/create-customer.dto.ts
> +    register_date: Date;
Eliminada el decorador @IsDate()  y la propiedad register_date

2023-09-19 21:45 UTC, dartorrejon commented on src/customers/entities/customer.entity.ts
> -  // TODO: relaciones
Comentario eliminado

2023-09-19 21:46 UTC, dartorrejon commented on src/orders/entities/order.entity.ts
>  //import { ShoppingCart } from '../../shopping-cart/entities/shopping-cart.entity.ts'; // Import your ShoppingCart entity here
Comentarios eliminados

2023-09-19 21:46 UTC, dartorrejon commented on src/orders/entities/order.entity.ts
>    // TODO: relaciones
Comentarios eliminados

2023-09-19 21:46 UTC, dartorrejon commented on src/shopping-cart/dto/create-shopping-cart.dto.ts
>  export enum Status {
Enum movido a una carpeta propia dentro de la carpeta src/

2023-09-19 21:48 UTC, dartorrejon commented on src/shopping-cart/entities/shopping-cart.entity.ts
> +  cart_prudocts: CartProduct[];
cambio realizado

2023-09-19 21:48 UTC, dartorrejon commented on src/shopping-cart/entities/shopping-cart.entity.ts
> +  @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' }) //No se si es lo correcto
cambio realizado

2023-09-19 21:50 UTC, dartorrejon commented on src/shopping-cart/dto/update-shopping-cart.dto.ts
> +export class UpdateShoppingCartDto extends PartialType(CreateShoppingCartDto) {}
Esto es lo unico que no entendi como hacerlo lo dejo tal cual para verlo en la reunion

2023-09-19 21:50 UTC, dartorrejon commented on src/shopping-cart/dto/create-shopping-cart.dto.ts
>      startedAt: Date
Me falto eliminar solo esta propiedad

2023-09-19 21:51 UTC, dartorrejon commented on src/shopping-cart/dto/create-shopping-cart.dto.ts
> +    @IsString()
modificado el status a OPEN por defecto

2023-09-19 23:29 UTC, Gaston71 reviewed
Veo que hiciste todos los cambios que sugirió Daniel. Bien ahí! 💪

2023-09-27 01:55 UTC, Gaston71 approved these changes
Aprobado.

2023-10-02 12:55 UTC, leinadpy approved these changes

2023-10-02 12:55 UTC, merged